#this will draw mulitple squares
import turtle
scr = turtle.Turtle()
scr.pensize(5)
scr.shape("turtle")
scr.left(90)
scr.forward(100)
scr.back(50)
scr.right(90)
scr.forward(40)
scr.left(90)
scr.forward(50)
scr.back(100)
scr.penup()
scr.right(90)
scr.forward(40)
scr.left(90)
scr.pendown()
scr.forward(50)
scr.penup()
scr.forward(25)
