#
turtle.pencolor("red")
turtle.circle(105)
turtle.pencolor("orange")
turtle.circle(95)
turtle.pencolor("yellow")
turtle.circle(85)
turtle.pencolor("green")
turtle.circle(75)
turtle.pencolor("light blue")
turtle.circle(65)
turtle.pencolor("blue")
turtle.circle(55)
turtle.pencolor("purple")
turtle.circle(45)
turtle.pencolor("pink")
turtle.circle(35)
